spring:
  application:
    name: product-catalog-service 
  datasource:
    url: jdbc:h2:mem:fieldconditionstatisticsdb
    username: sa
    password:
    driverClassName: org.h2.Driver
  h2:
    console:
       enabled: true
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true